language: node_js
notifications:
  email:
  - yiminghe@gmail.com
node_js:
- 0.11
before_script:
- node --harmony server &
- npm install gulp bower mocha-phantomjs -g
- bower install
- gulp mx
- phantomjs --version
script:
- npm run browser-test
- npm run browser-test-build
- npm run browser-test-cover